const HANDLE_LOGIN = 'HANDLE_LOGIN';
const HANDLE_LOGOUT = 'HANDLE_LOGOUT';
const ADD_EVALUATION = 'ADD_EVALUATION';
const GET_EVALUATIONS = 'GET_EVALUATIONS';
const START_LOADING = 'START_LOADING';
const STOP_LOADING = 'STOP_LOADING';

export {
  HANDLE_LOGIN,
  HANDLE_LOGOUT,
  ADD_EVALUATION,
  GET_EVALUATIONS,
  START_LOADING,
  STOP_LOADING,
};
