const HANDLE_LOGIN = 'HANDLE_LOGIN';
const HANDLE_LOGOUT = 'HANDLE_LOGOUT';
const ADD_EVALUATION = 'ADD_EVALUATION';
const GET_EVALUATIONS = 'GET_EVALUATIONS';
const CLEAN_EVALUATIONS = 'CLEAN_EVALUATIONS';
const START_LOADING = 'START_LOADING';
const STOP_LOADING = 'STOP_LOADING';
const SHOW_ERROR = 'SHOW_ERROR';
const DISMISS_ERROR = 'DISMISS_ERROR';

export {
  HANDLE_LOGIN,
  HANDLE_LOGOUT,
  ADD_EVALUATION,
  GET_EVALUATIONS,
  CLEAN_EVALUATIONS,
  START_LOADING,
  STOP_LOADING,
  SHOW_ERROR,
  DISMISS_ERROR,
};
