const HANDLE_LOGIN = 'HANDLE_LOGIN';
const HANDLE_LOGOUT = 'HANDLE_LOGOUT';
const ADD_EVALUATION = 'ADD_EVALUATION';
const GET_EVALUATIONS = 'GET_EVALUATIONS';

export {
  HANDLE_LOGIN,
  HANDLE_LOGOUT,
  ADD_EVALUATION,
  GET_EVALUATIONS,
};
